name: project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.6
  user_profile_avatar: ^0.1.2
  path_provider: ^2.1.3
  flutter_cache_manager: ^3.3.3
  syncfusion_flutter_charts: ^26.2.4
  fl_chart: ^0.68.0
  delightful_toast: ^1.1.0
  get: ^4.6.6
  http: ^1.2.2
  shared_preferences: ^2.2.3
  another_flushbar: ^1.10.28

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  

flutter:
  uses-material-design: true
  assets:
    - assets/logo/Management.png
    - assets/images/work2.png
    - assets/images/work1.png
    - assets/images/profile.png
    - assets/images/navigator1.png
    - assets/images/navigator2.png
    - assets/images/navigator3.png
    - assets/images/add-product.png
    - assets/images/supply.png
    - assets/images/user-add.png
    - assets/images/product-add.png
    - assets/images/supplier-add.png
  fonts:
    - family: JetBrainsMono
      fonts:
        - asset: assets/fonts/ttf/JetBrainsMono-Regular.ttf
        - asset: assets/fonts/ttf/JetBrainsMono-Bold.ttf
          weight: 700
        - asset: assets/fonts/ttf/JetBrainsMono-Italic.ttf
          style: italic
